services:

  demo-backend:
    # build:
    #   context: .
    #   dockerfile: apps/backend/Dockerfile
    image: full-stack-nextjs-demo-backend:latest
    ports:
      - "3001:3001"
    restart: always
    networks:
      - custom-network
    env_file:
      - ./apps/backend/.env
    healthcheck:
      test: ["CMD", "/nodejs/bin/node", "dist/health_check.js"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  demo-frontend:
    image: full-stack-nextjs-demo-frontend:latest
    # build:
    #   context: .
    #   dockerfile: apps/frontend/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pr-1.rule=Host(`pr-1.localhost`)"
      - "traefik.http.routers.pr-1.entrypoints=web"
      - "traefik.http.services.pr-1.loadbalancer.server.port=3000"
    ports:
      - "3000:3000"
    networks:
      - custom-network
    env_file:
      - ./apps/frontend/.env
    depends_on:
      demo-backend:
        condition: service_healthy

networks:
  custom-network:
    external: true