name: production-ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, closed]
jobs:
  ci-pipeline:
    if: github.event_name == 'push' || github.event.action != 'closed'
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: setup pnpm manager
        uses: pnpm/action-setup@v4
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: lint
        run: pnpm lint
      - name: build
        run: pnpm build

  preview:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    needs: ci-pipeline
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set pr number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: start preview
        env:
          PORT: ${{secrets.PORT}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_PORT: ${{secrets.DB_PORT}}
          NEXT_PUBLIC_BASE_URI: ${{secrets.NEXT_PUBLIC_BASE_URI}}
        run: |
          docker compose \
          -p pr-${PR_NUMBER} \
          up \
          --build \
          -d
      - name: debug
        run: echo "PR_NUMBER is:'${PR_NUMBER}'"

      - name: preview url
        run: |
          echo "## 🚀 Preview Deployment" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🌐 **Preview:** [http://pr-${PR_NUMBER}.localhost](http://pr-${PR_NUMBER}.localhost)" >> $GITHUB_STEP_SUMMARY

  cleanup:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set pr number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> "$GITHUB_ENV"

      - name: Remove preview
        run: |
          docker compose -p pr-${PR_NUMBER} down

  notify-slack:
    needs:
      - ci-pipeline
      - preview
      - cleanup
    if: ${{always() && (needs.cleanup.result == 'failure' || needs.preview.result == 'failure' || needs.ci-pipeline.result == 'failure')}}
    runs-on: self-hosted
    steps:
      - name: send slack notification
        run: |
          curl -X POST \
          -H 'Content-type: application/json' \
          --data '{
            "text": "ci/cd pipeline failed \nrepository:${{github.repository}} \nbranch:${{github.ref_name}} \nworkflow:${{github.workflow}} \nrun:${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
          }'\
          "${{secrets.SLACK_WEBHOOK_URL}}"

